// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRNG3aeMvFWD5ypo9I_Jw8cLDew7iMto',
    appId: '1:971851568528:web:d3cf744a03c7b2ec608f15',
    messagingSenderId: '971851568528',
    projectId: 'encuadrado-e1dd8',
    authDomain: 'encuadrado-e1dd8.firebaseapp.com',
    storageBucket: 'encuadrado-e1dd8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtlupBhGIE_1kOQXaBWOt0Xc_S1ptmtbI',
    appId: '1:971851568528:android:dcc31b5ca55190f0608f15',
    messagingSenderId: '971851568528',
    projectId: 'encuadrado-e1dd8',
    storageBucket: 'encuadrado-e1dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DJir3YLBZPjF_UvtZBI9jXmrWCi5nMk',
    appId: '1:971851568528:ios:dd2a6a5dbc516ea1608f15',
    messagingSenderId: '971851568528',
    projectId: 'encuadrado-e1dd8',
    storageBucket: 'encuadrado-e1dd8.firebasestorage.app',
    iosBundleId: 'com.example.encuadrado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DJir3YLBZPjF_UvtZBI9jXmrWCi5nMk',
    appId: '1:971851568528:ios:dd2a6a5dbc516ea1608f15',
    messagingSenderId: '971851568528',
    projectId: 'encuadrado-e1dd8',
    storageBucket: 'encuadrado-e1dd8.firebasestorage.app',
    iosBundleId: 'com.example.encuadrado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrRNG3aeMvFWD5ypo9I_Jw8cLDew7iMto',
    appId: '1:971851568528:web:b1310b16524c2a6c608f15',
    messagingSenderId: '971851568528',
    projectId: 'encuadrado-e1dd8',
    authDomain: 'encuadrado-e1dd8.firebaseapp.com',
    storageBucket: 'encuadrado-e1dd8.firebasestorage.app',
  );
}
